#!/usr/bin/env node
// make_icon_module.mjs: writes web/icons.js from firmware/muse_icons.h.
//
// What: reads the two tables of muse_icons.h (ICON_NAMES, sorted MDI names, and
//   ICON_ALIASES, the event names and German words) and writes them as an ES module, so
//   the web display resolves the same icon names to the same Material Design Icons
//   codepoints as the box, in the same order (closest() in scene.js walks the names in
//   this order, and the first of two equally close names wins, as on the box).
// Why: one source of truth. The firmware's table is generated from
//   muse_icon_glyphs.yaml and the font by tools/make_icon_table.py; this script only
//   mirrors it, it never adds a name.
// Pitfalls:
//   * Run it after every change to muse_icons.h and commit icons.js with it; the test
//     test/icons.test.js fails when the two drift apart.
//   * The MDI version is read from the header's comment, so the page loads the same
//     font release the box compiles in.
// Usage (from the project root or from web/):
//   node web/tools/make_icon_module.mjs [--dry-run]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../../firmware/muse_icons.h");
const target = resolve(here, "../icons.js");
const dryRun = process.argv.includes("--dry-run");

const header = readFileSync(source, "utf8");
const version = (header.match(/Material Design Icons ([\d.]+)/) || [])[1];
if (!version) throw new Error("no MDI version in " + source);

function table(name) {
  const block = header.match(new RegExp(name + "\\[\\] = \\{([\\s\\S]*?)\\};"));
  if (!block) throw new Error("no table " + name + " in " + source);
  const rows = [];
  for (const m of block[1].matchAll(/\{"([^"]+)",\s*0x([0-9A-Fa-f]+)\}/g)) rows.push([m[1], parseInt(m[2], 16)]);
  return rows;
}

const names = table("ICON_NAMES");
const aliases = table("ICON_ALIASES");
const count = Number((header.match(/ICON_COUNT = (\d+)/) || [])[1]);
const aliasCount = Number((header.match(/ICON_ALIAS_COUNT = (\d+)/) || [])[1]);
if (names.length !== count || aliases.length !== aliasCount) {
  throw new Error(`table sizes differ: ${names.length}/${count} names, ${aliases.length}/${aliasCount} aliases`);
}
for (let i = 1; i < names.length; i++) {
  if (names[i - 1][0] >= names[i][0]) throw new Error("ICON_NAMES is not sorted at " + names[i][0]);
}

const rows = (list) => list.map(([n, cp]) => `  ["${n}", 0x${cp.toString(16).toUpperCase()}],`).join("\n");
const out = `// icons.js: generated by tools/make_icon_module.mjs from firmware/muse_icons.h, do not edit.
// Material Design Icons ${version} (Apache 2.0): the icons a Muse scene can use, by their
// MDI name, and the other words for them (event names, German words). The order matters:
// closest() in scene.js walks ICON_NAMES first, then ICON_ALIASES, like the box.

export const MDI_VERSION = "${version}";

// Sorted by name, like the firmware's binary-searched table.
export const ICON_NAMES = [
${rows(names)}
];

// Other words for an icon, normalised like scene.js normalises input.
export const ICON_ALIASES = [
${rows(aliases)}
];

export const ICON_MAP = new Map([...ICON_NAMES, ...ICON_ALIASES]);
export const ICON_WORDS = [...ICON_NAMES.map((r) => r[0]), ...ICON_ALIASES.map((r) => r[0])];
`;

if (dryRun) {
  console.log(`would write ${target}: ${names.length} names, ${aliases.length} aliases, MDI ${version}`);
} else {
  writeFileSync(target, out);
  console.log(`wrote ${target}: ${names.length} names, ${aliases.length} aliases, MDI ${version}`);
}
